### ISSUE TITLE
Logs Errors Object Lower

### ISSUE THREAD

**Issue by Nicoco06** [djoole/couchpotato.provider.t411#14]
Bonjour,
En installant cette version j'ai ce message qui apparait dans CouchPotato.
Avez-vous une idée, aussi la recherche s'effectue quand même ?

Merci pour votre assistance,

```
08-11 06:27:40 ERROR [                     t411] Failed to parse T411: Traceback (most recent call last):
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/t411/main.py", line 105, in _searchOnTitle
    'name': replaceTitle(release_name, title, newTitle),
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/t411/main.py", line 249, in replaceTitle
    newTitle = newTitleI.lower()
AttributeError: 'NoneType' object has no attribute 'lower' 
```

**Comment by djoole** [comment]
Merci pour le bug report. Le commit précédent devrait corriger le problème.
