### ISSUE TITLE
Fichiers installés mais T411 n'apparait pas

### ISSUE THREAD

**Issue by gogui51** [djoole/couchpotato.provider.t411#21]
Bonjour,

j'ai déplacé les fichiers dans le bon répertoire (je pense !) mais même après un "restart" le provider n'apparait pas.

Voici où sont copier les fichiers :
osmc@osmc:/home/couchpotato/.couchpotato/customs_plugin/t411$ ls
**init**.py  main.py

Je ne comprends pas où j'ai merdé !

Merci pour votre aide !
Greg

**Comment by djoole** [comment]
Ca a l'air effectivement bon.
Tu peux poster les logs en DEBUG du démarrage de ton CP?

**Comment by kaosphere34** [comment]
Bonjour,

Je me permet de rebondir sur ce sujet car j'ai la même erreur "ImportError: No module named ast" : 

DEBUG
[  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "C:\Users\kaosphere\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\kaosphere\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper__init__.py", line 37, in import_module
  File "C:\Users\kaosphere\AppData\Roaming\CouchPotato\custom_plugins\t411__init__.py", line 1, in <module>
  File "C:\Users\kaosphere\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 16, in <module>
ImportError: No module named ast

Et surtout MERCI !
Eric M.

**Comment by djoole** [comment]
Il vous manque le module python **ast** qui fait partie de l'installation standard de Python.
Réinstallez ce dernier.
