### ISSUE TITLE
Error fetching info from T411

### ISSUE THREAD

**Issue by teimahu** [djoole/couchpotato.provider.t411#33]
Hello,

I'm using your plugin, but I didn't succeed in getting torrent file from T411 website.
Don't know why, but I got the following error in the log page:

Note: DSM version is 6.0.2-8451 Update 2

```
10-09 20:18:14 INFO
[hpotato.core.plugins.base] Opening url: get https://www.t411.ch/torrents/search/?search=%28the%20ardennes%29%7C%28les%20ardennes%29%20dvdrip%7C(dvd%26rip), data: []
10-09 20:18:15 ERROR
[ couchpotato.core.event] Error in event "quality.single", that wasn't caught: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/quality/main.py", line 117, in single quality = db.get('quality', identifier, with_doc = True)['doc'] File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database.py", line 944, in get raise RecordNotFound("Not found") RecordNotFound: Not found encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)
10-09 20:18:15 ERROR
[ couchpotato.core.event] Error in event "movie.searcher.single", that wasn't caught: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/movie/searcher.py", line 200, in single log.info('Search for %s in %s%s', (default_title, quality['label'], ' ignoring ETA' if always_search or ignore_eta else '')) TypeError: 'NoneType' object has no attribute '__getitem__' encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)
```

May you point me in the appropriate direction ?
Thanks.

Mathieu

**Comment by djoole** [comment]
No idea sorry.
Are you sure to use the ruudburger version of CP?
https://github.com/CouchPotato/CouchPotatoServer
If so, please post debug logs.

**Comment by djoole** [comment]
No answer
